-- SpendWise initial schema.
-- Generated from the current Hibernate/DataGrip DDL export and normalized for Flyway.

CREATE SCHEMA IF NOT EXISTS spendwise;
SET search_path TO spendwise;

create table app_user
(
    enabled          boolean,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    email            varchar(255)
        unique,
    name             varchar(255),
    password_hash    varchar(255),
    profile_picture  varchar(255),
    role             varchar(255)
        constraint app_user_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    surname          varchar(255)
);
create table budget
(
    enabled          boolean,
    month            integer,
    year             integer,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkj0sapqxycpvg4updwcvqdq1ti
            references app_user,
    description      varchar(255)
);
create table category
(
    enabled          boolean,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkrlg1obihj1el9rttiseudaehs
            references app_user,
    icon             varchar(2048),
    name             varchar(255),
    type             varchar(255)
        constraint category_type_check
            check ((type)::text = ANY
                   ((ARRAY ['INCOME'::character varying, 'EXPENSE'::character varying, 'SAVING'::character varying, 'DEBT'::character varying, 'INVESTMENT'::character varying])::text[]))
);
create table currency
(
    enabled          boolean,
    is_default       boolean,
    symbol           varchar(3),
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkk11nc25433mxpsbxbjqspurtt
            references app_user,
    icon             varchar(2048),
    name             varchar(255)
);
create table income
(
    amount_ars       numeric(38, 2),
    amount_usd       numeric(38, 2),
    date             date,
    creation_date    timestamp(6),
    currency_id      bigint
        constraint fknmcb472jap6lfofx3dbvxtjeo
            references currency,
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    source_id        bigint
        constraint fkj315f5hwnk2jeaw0cumhax9od
            references category,
    user_id          bigint
        constraint fks6fo7ed1xqyhyvarpju7erktf
            references app_user,
    description      varchar(255)
);
create table issuing_entity
(
    enabled          boolean,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkanwvbhchicvtt3aax3l9bqefo
            references app_user,
    icon             varchar(2048),
    description      varchar(255)
);
create table merchant_shortcut
(
    enabled          boolean,
    category_id      bigint
        constraint fkm5vt53xw4lt62r7gyj79hwems
            references category,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkiqw6xbt2t2eg7kon65ph8oo6n
            references app_user,
    icon             varchar(2048),
    name             varchar(255)
);
create table password_reset_token
(
    creation_date    timestamp(6),
    expiry_date      timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkli7wollcmb8tibymo3s94o57h
            references app_user,
    token            varchar(255)
);
create table payment_method
(
    enabled             boolean,
    is_default          boolean,
    payment_method_type smallint
        constraint payment_method_payment_method_type_check
            check ((payment_method_type >= 0) AND (payment_method_type <= 4)),
    creation_date       timestamp(6),
    id                  bigint generated by default as identity
        primary key,
    issuing_entity_id   bigint
        constraint fkr6rwr83oibqukkncp4maunh0b
            references issuing_entity,
    last_update_date    timestamp(6),
    user_id             bigint
        constraint fk4wgd887wvmnvf3vmqdlgtfvs4
            references app_user,
    icon_url            varchar(255),
    name                varchar(255)
);
create table debt
(
    amount_ars        numeric(38, 2),
    amount_usd        numeric(38, 2),
    cancelled         boolean,
    date              date,
    due_date          date,
    personal          boolean,
    creation_date     timestamp(6),
    currency_id       bigint
        constraint fkt42f19hrjp7blgek4k0hhrlmp
            references currency,
    id                bigint generated by default as identity
        primary key,
    issuing_entity    bigint
        constraint fkf75dv7hj578hxe7vw8n3vdss4
            references issuing_entity,
    last_update_date  timestamp(6),
    payment_method_id bigint
        constraint fk1wa21elm632rnm9nl6mpoqhay
            references payment_method,
    user_id           bigint
        constraint fk1ye3g2nedtralf4h80mq3khp7
            references app_user,
    creditor          varchar(255),
    description       varchar(255)
);
create table expense
(
    amount_ars        numeric(38, 2),
    amount_usd        numeric(38, 2),
    date              date,
    micro_expense     boolean,
    category_id       bigint
        constraint fkmvjm59reb5i075vu38bwcaqj6
            references category,
    creation_date     timestamp(6),
    currency_id       bigint
        constraint fkfkdvf1ivs3l31iy5tf5ap3kul
            references currency,
    id                bigint generated by default as identity
        primary key,
    last_update_date  timestamp(6),
    payment_method_id bigint
        constraint fkp763mx9qvy2pv4eisrwrqcdo6
            references payment_method,
    user_id           bigint
        constraint fk18n87d1yx5s1pr35h5vy9gycr
            references app_user,
    description       varchar(255)
);
create table merchant_binding
(
    category_id       bigint
        constraint fk6o3y33h6flrl4h6xlxob7feni
            references category,
    creation_date     timestamp(6),
    id                bigint generated by default as identity
        primary key,
    last_update_date  timestamp(6),
    payment_method_id bigint
        constraint fk5w0hsgpjubt7wykxudmaybd1t
            references payment_method,
    user_id           bigint
        constraint fkckdy231qba5n3i7g55opss6fu
            references app_user,
    description       varchar(255),
    merchant_name     varchar(255),
    unique (user_id, merchant_name)
);
create table personal_debt
(
    amount_ars       numeric(38, 2),
    amount_usd       numeric(38, 2),
    cancelled        boolean,
    date             date,
    due_date         date,
    creation_date    timestamp(6),
    currency_id      bigint
        constraint fkc1rsagv6ov102vh57pxldx3a8
            references currency,
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        constraint fkmon0t4laxcp0od106r24mva0
            references app_user,
    creditor         varchar(255),
    description      varchar(255)
);
create table recommended_category
(
    display_order    integer,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    icon             varchar(255),
    name             varchar(255),
    type             varchar(255)
        constraint recommended_category_type_check
            check ((type)::text = ANY
                   ((ARRAY ['INCOME'::character varying, 'EXPENSE'::character varying, 'SAVING'::character varying, 'DEBT'::character varying, 'INVESTMENT'::character varying])::text[]))
);
create table recommended_currency
(
    default_selected boolean,
    display_order    integer,
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    symbol           varchar(20),
    name             varchar(255)
);
create table recommended_entity
(
    creation_date    timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    icon_url         varchar(500),
    name             varchar(255)
);
create table recommended_merchant_shortcut
(
    display_order           integer,
    creation_date           timestamp(6),
    id                      bigint generated by default as identity
        primary key,
    last_update_date        timestamp(6),
    recommended_category_id bigint
        constraint fkqy2ew7l343awrrc1ppo9vajie
            references recommended_category,
    icon                    varchar(255),
    name                    varchar(255)
);
create table recurrent_expense
(
    amount_ars        numeric(38, 2),
    amount_usd        numeric(38, 2),
    day_of_month      integer,
    enabled           boolean,
    category_id       bigint
        constraint fkqaeh95ghwcebnaxadu20wmyno
            references category,
    creation_date     timestamp(6),
    currency_id       bigint
        constraint fkjj6944dt64gm1yawbretjm3su
            references currency,
    id                bigint generated by default as identity
        primary key,
    last_update_date  timestamp(6),
    payment_method_id bigint
        constraint fkn4fac9409fjfk32yxq81fqi1c
            references payment_method,
    user_id           bigint
        constraint fkrx9gqqnswhc8860n2mnpeutbd
            references app_user,
    icon              varchar(2048),
    description       varchar(255)
);
create table budget_recurrent_expense
(
    budget_id            bigint not null
        constraint fk2c6pxuet2av9423me18j1a4v3
            references budget,
    recurrent_expense_id bigint not null
        constraint fkgq44basv8iwgvdky9wdje92y2
            references recurrent_expense
);
create table recurrent_expense_record
(
    amount_spent_in_dollars numeric(38, 2),
    amount_spent_in_pesos   numeric(38, 2),
    cancelled               boolean,
    month                   integer,
    year                    integer,
    creation_date           timestamp(6),
    expense_id              bigint
        constraint fk2bhfhcix2esj7syblllu7wism
            references expense,
    id                      bigint generated by default as identity
        primary key,
    last_update_date        timestamp(6),
    recurrent_expense_id    bigint
        constraint fkngscfm34trw22jwfyjyp0eggj
            references recurrent_expense,
    user_id                 bigint
        constraint fkfol832hlghgdohinh75djy8fu
            references app_user
);
create table refresh_token
(
    creation_date    timestamp(6),
    expires_at       timestamp(6) with time zone not null,
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint                      not null
        constraint fk5wkt2p042y3lwltk29cvpxuh
            references app_user,
    token            varchar(255)                not null
        unique
);
create table savings_wallet
(
    enabled             boolean,
    savings_wallet_type smallint
        constraint savings_wallet_savings_wallet_type_check
            check ((savings_wallet_type >= 0) AND (savings_wallet_type <= 4)),
    creation_date       timestamp(6),
    id                  bigint generated by default as identity
        primary key,
    issuing_entity_id   bigint
        constraint fkt052fhbepvl0mlrytsyu6c0b4
            references issuing_entity,
    last_update_date    timestamp(6),
    user_id             bigint
        constraint fkckha9g0lmkg26gd3ahv0flhit
            references app_user,
    icon                varchar(255),
    name                varchar(255)
);
create table saving
(
    amount_ars        numeric(38, 2),
    amount_usd        numeric(38, 2),
    date              date,
    creation_date     timestamp(6),
    currency_id       bigint
        constraint fkpe0j4qkdax1iv4h2j93ln3ah2
            references currency,
    id                bigint generated by default as identity
        primary key,
    last_update_date  timestamp(6),
    savings_wallet_id bigint
        constraint fkc0f76ibic9a5syaw9x9abywrg
            references savings_wallet,
    user_id           bigint
        constraint fk2yy23b3s3da8r06a8nafdnr1f
            references app_user,
    description       varchar(255)
);
create table verification_token
(
    creation_date    timestamp(6),
    expiry_date      timestamp(6),
    id               bigint generated by default as identity
        primary key,
    last_update_date timestamp(6),
    user_id          bigint
        unique
        constraint fk1tc78gv9fnf5oyv26e2uy0xy0
            references app_user,
    token            varchar(255)
);
